export enum ActivityCode {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  USER_IMPERSONATION = 'USER_IMPERSONATION',
  // Company related activities
  COMPANY_CREATE = 'COMPANY_CREATE',
  COMPANY_UPDATE = 'COMPANY_UPDATE',
  // Group related activities
  GROUP_CREATE = 'GROUP_CREATE',
  GROUP_UPDATE = 'GROUP_UPDATE',
  // Delete events (optional)
  COMPANY_DELETE = 'COMPANY_DELETE',
  GROUP_DELETE = 'GROUP_DELETE',
  USER_DELETE = 'USER_DELETE',
}
